# Generated by Django 4.2.16 on 2024-11-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=13),
        ),
    ]
